version: '3'

services:
  php:
    container_name: swoft_app
    image: php73-apache
    build:
      context: .docker/
      dockerfile: Dockerfile
      args:
        VERSION: 7.3.6
    restart: always
    ports:
      - "8001:18306"
    links:
      - pgsql
    volumes:
      - "./:/var/www/html"
      - "./.docker/httpd/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    environment:
      TZ: Asia/Tokyo

  pgsql:
    container_name: swoft_app_postgresql_db
    image: postgres:latest
    ports:
      - "54321:5432"
    volumes:
      - "./.docker/var/pg_data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: swoft_db1
      POSTGRES_USER: swoft_user
      POSTGRES_PASSWORD: secret
  redis:
    container_name: swoft_app_redis
    image: redis:latest
